baseURL = 'https://shirishgoyal.github.io/petal-stack/'
languageCode = 'en-us'
title = 'PETAL Stack'

theme = "hugo-ink"
paginate = 8

copyright = "© Shirish Goyal. All Rights Reserved."

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "A potion of Phoenix, Elixir, Tailwind, Alpine and LiveView"

	# Optional 64x64 avatar image.
	avatar = "/petal-stack/penguin.png"

	favicon = "/petal-stack/avatar.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

#[[params.social]]
#name = "Github"
#icon = "github"
#url = "https://github.com/shirishgoyal"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"